### ISSUE TITLE
Creation of a TableView not possible

### ISSUE THREAD

**Issue by zilti** [scalafx/scalafx#137] opened 2014-06-08 16:25 UTC
I tried to create a table using the example code from ScalaFX. I'm using Java 8 and Scala 2.11.1. It doesn't work, all I get is this:

``` scala
Error:(26, 11) type mismatch;
 found   : scalafx.scene.control.TableColumn[Person,String]
 required: javafx.scene.control.TableColumn[Person, ?]
          new TableColumn[Person, String] {
          ^
```

**Comment by norbusan** [comment] 2017-11-17 06:10
The same happens with `TreeItem`s in (at least) a `TreeTableView`. Here is  a complete example based on the above code, that exhibits the problem. I have to add `import scalafx.scene.control.TreeTableColumn._`, to get the cell factory working, but even with importing `TreeItem._` I cannot compile this example and get:

```
[error]  found   : Seq[javafx.scene.control.TreeItem[Person]]
[error]  required: Seq[scalafx.scene.control.TreeItem[Person]]
[error]               table.root.value.children = foo
```

Is there any chance that this gets fixed at some point? Or are there any suggestions how to overcome it? I tried to convert with `asInstanceOf` but that failed.

Thanks

Norbert


```
import javafx.scene.control

import scalafx.Includes._
import scalafx.scene.control.TreeTableColumn._
import scalafx.scene.control.TreeItem._
import scalafx.application.JFXApp.PrimaryStage
import scalafx.application.JFXApp
import scalafx.scene.Scene
import scalafx.scene.layout._
import scalafx.scene.control._
import scalafx.scene.control.TreeTableView

import scalafx.scene.control.Button
import scalafx.scene.paint.Color
import scalafx.beans.property.{ObjectProperty, StringProperty}
import scalafx.collections.ObservableBuffer


// TableTester.scala
object TableTester extends JFXApp {

  val characters = ObservableBuffer[Person](
    new Person("Peggy", "Sue", "123", Color.Violet),
    new Person("Rocky", "Raccoon", "456", Color.GreenYellow),
    new Person("Bungalow ", "Bill", "789", Color.DarkSalmon)
  )

  val table = new TreeTableView[Person](
    new TreeItem[Person](new Person("","","",Color.Red)) {
      expanded = true
      children = characters.map(new TreeItem[Person](_))
    }) {
    columns ++= List(
      new TreeTableColumn[Person, String] {
        text = "First Name"
        cellValueFactory = {
          _.value.value.value.firstName
        }
        prefWidth = 180
      },
      new TreeTableColumn[Person, String]() {
        text = "Last Name"
        cellValueFactory = {
          _.value.value.value.lastName
        }
        prefWidth = 180
      }
    )
  }

  stage = new PrimaryStage {
    title = "Simple Table View"
    scene = new Scene {
      content = new VBox() {
        children = List(
          new Button("Test it") {
            onAction = p => {
              val foo: Seq[control.TreeItem[Person]] = table.root.value.children.map(p => {
                val bar: TreeItem[Person] = p
                p
              }).toSeq
              table.root.value.children = foo
            }
          },
          table)
      }
    }
  }
}

// Person.scala
class Person(firstName_ : String, lastName_ : String, phone_ : String, favoriteColor_ : Color = Color.Blue) {

  val firstName = new StringProperty(this, "firstName", firstName_)
  val lastName = new StringProperty(this, "lastName", lastName_)
  val phone = new StringProperty(this, "phone", phone_)
  val favoriteColor = new ObjectProperty(this, "favoriteColor", favoriteColor_)

  firstName.onChange((x, _, _) => System.out.println(x.value))
}
```

**Comment by jpsacha** [comment] 2021-05-16 15:05
This issue can no longer be reproduced with Scala 2.13 and Scala 3 compilers. Looks like a bug in Scala 2.12.
Closing as it looks like a Scala compiler bug that was fixed

**Closed by jpsacha** 2021-05-16 15:05 UTC
Labels: help wanted
