### ISSUE TITLE
Type Mismatch in adding Panes to children of a Pane

### ISSUE THREAD

**Issue by benedictleejh** [scalafx/scalafx#181] opened 2015-02-07 15:10 UTC
This is related to #23 and #122. When trying to add `Pane`s to the children of a `Pane`, the compile will fail with a type mismatch.

This code:

``` scala
val content = new VBox(5) {
    autosize()

    children += new HBox(5) {
      alignment = Pos.CenterLeft
      autosize()

      children += new Label("Node name:")
      children += new TextField()
    }
    children += new Label("Node Content")
    children += textEditor
  }
```

fails with

```
type mismatch;
 found   : scalafx.scene.layout.HBox
 required: javafx.scene.Node
    children += new HBox(5) {
                ^
```

Moving the `HBox` out to a variable solves the error, but it's obviously extremely cumbersome to do this for all such instances, and it clutters up the code with excessive assignments.

**Comment by jpsacha** [comment] 2015-10-30 22:40
I am not sure how this could be fixed. There is something with implicit conversion not being applied as expected (though the conversion works if imported directly, see second workaround below) . There are two workarounds that do do not require creating additional variable.

First is to add `.delegate` to explicitly convert to JavaFX type:

```scala
  children += new HBox(5) {
    ...
  }.delegate
```

Second one is to explicitly import implicit conversion :)
```scala
import scalafx.scene.layout.LayoutIncludes.jfxHBox2sfx

...

  children += new HBox(5) {
    ...
  }
```

**Comment by jpsacha** [comment] 2021-05-16 15:31
This issue can no longer be reproduced with Scala 2.13 and Scala 3 compilers. Looks like a bug in Scala 2.12.
Closing as it looks like a Scala compiler bug that was fixed.

**Closed by jpsacha** 2021-05-16 15:31 UTC
Labels: help wanted
