### ISSUE TITLE
Issues with reading fxml file after creating jar

### ISSUE THREAD

**Issue by yadavan88** [scalafx/scalafx#200] opened 2015-05-15 06:41 UTC
I am not sure if this is specific to scalafx or in general with reading file as resource in jar file. I have posted the same question in StackOverflow(http://stackoverflow.com/questions/30237469/issues-with-reading-xml-file-after-creating-jar) as well, but got no response so far. I am stuck from yesterday with this issue, not able to do anything. 

The issue is that, when I create a jar file and execute it, the application is not able to find the fxml file. But it works fine in IDE.

object App extends JFXApp {

  val root = FXMLView(getClass.getResource("/com/app/adt/Home.fxml"),
    new DependenciesByType(Map(
      typeOf[TestDependency] -> new TestDependency("ADT"))))

  stage = new JFXApp.PrimaryStage() {
    title = "ADT"
    scene = new Scene(root)
  }
}

I am getting the error as below:

Caused by: javafx.fxml.LoadException:
file:/adt-app_2.11-1.3-SNAPSHOT-one-jar.jar!/main/adt-app_2.11-1.3-S
NAPSHOT.jar!/com/app/adt/Home.fxml

        at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2611)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2589)
        at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2435)
        at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2403)
        at scalafxml.core.FXMLView$.apply(FXMLView.scala:17)

Can anyone help me to resolve this?

**Comment by jpsacha** [comment] 2015-05-16 19:46
I am closing this issue since it does not look like an ScalaFX issue. Rather, due to OneJar packaging the URL of the FXML file is not usable by JavaFX. 
There are some suggested solutions for using URL resources with OneJar, for instance this answer [question](http://stackoverflow.com/questions/861500/url-to-load-resources-from-the-classpath-in-java).

It is always good to provide a small sample project that can be used to reproduce the issue, especially in cases when the setup is unusual like yours (OneJar). This may help somebody that may want to try to help but does not have time to research and reproduce the setup.

**Closed by jpsacha** 2015-05-16 19:46 UTC
